apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scale
  namespace: argocd
spec:
  destination:
    namespace: myphp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./scaling
    repoURL: https://github.com/marconesns/php-scaling.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
