apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: php-scaling
  name: php-scaling
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: php-scaling
  type: NodePort
status:
  loadBalancer: {}
